name: socolse_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.4
  flutter_map_marker_popup: ^2.1.1+1
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  get: 4.6.1
  latlng: ^0.1.0
  location: ^4.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/audio/
  uses-material-design: true
